PACKAGES = $(shell go list ./... | grep -v '/vendor/')
VETARGS?=-asmdecl -atomic -bool -buildtags -copylocks -methods \
-nilfunc -printf -rangeloops -shift -structtags -unsafeptr
EXTERNAL_TOOLS=\
github.com/kardianos/govendor \
	github.com/mitchellh/gox \
	golang.org/x/tools/cmd/cover \
	github.com/axw/gocov/gocov \
	gopkg.in/matm/v1/gocov-html \
	github.com/ugorji/go/codec/codecgen

# list only our .go files i.e. exlcudes any .go files from the vendor directory
GOFILES_NOVENDOR = $(shell find . -type f -name '*.go' -not -path "./vendor/*")
CTLNAME=golangUT
format:
	@echo "--> Running go fmt"
cover:
	go list ./... | grep -v vendor | xargs -n1 go test --cover
@go fmt $(PACKAGES)
install: bin/${CTLNAME}
install -o root -g root -m 0755 ./bin/${CTLNAME} /usr/local/bin/${CTLNAME}
